#!/bin/bash

if test $# -lt 5 ; then
  echo "USAGE: `basename $0` EXTENSION_FILE COMPILER LOWER_COMPILER_DIR LOWER_COMPILER COMPILER_ARGUMENTS" ;
  exit 1;
fi
extFile=$1 ;
compiler=$2 ;
lowerCompilerDir=$3 ;
lowerCompiler=$4 ;
compilerArgs="${@:5}" ;

origDir=`pwd` ;
rm -f prog.${extFile} ;
./bin/${compiler} ${compilerArgs}

if test $? -ne 0 ; then
  exit 1;
fi

if ! test -f prog.${extFile} ; then
  exit 1;
fi

pushd ./ ;
cd ${lowerCompilerDir} ;
./${lowerCompiler} ${origDir}/prog.${extFile} ;
if test $? -ne 0 ; then
  exit 1;
fi
if ! test -f a.out ; then
  exit 1;
fi
mv a.out ${origDir} ;
popd ;

exit 0
